### ISSUE TITLE
Compatibility with Sublime 3

### ISSUE THREAD

**Issue by orschiro** [fjl/Sublime-Missing-Palette-Commands#9]
Hi there,

Many thanks for this add-on!

Is it also compatible with Sublime Text 3?

Robert

**Comment by fjl** [comment]
It is compatible. You can use the st3 branch for sublime text 3.

**Comment by orschiro** [comment]
Thanks for your quick reply!

Installed the st3 branch. 

Identified at least one doubling with `Toggle Menu View` command:

![screenshot](https://cloud.githubusercontent.com/assets/170947/5610554/adcc6a78-94b9-11e4-8518-3f96fa5d4291.png)
